Metrics/LineLength:
  Max: 300

Metrics/AbcSize:
  Max: 100
  
Metrics/BlockLength:
  Max: 50

Metrics/MethodLength:
  Max: 50

Metrics/ParameterLists:
  Max: 10

Metrics/ClassLength:
  Max: 200

AllCops:
 Exclude:
     - 'impls/*'
